spring:
  profiles:
    active:
      - dubbo
  dubbo:
  
    application:
      name: demo-provider
      owner: laolei
      
#####################################################扫描注解的包###############################################################
    base-package: com.test.dubbo.provider
#####################################################扫描注解的包###############################################################
    
  
#####################################################发布者通用配置信息###############################################################
    provider:
      retries: -1
#      accesslog:
#      delay: 
#      deprecated: 
#      document: 
#      dynamic: 
#      executes: 
#      group: 
#      id: 
#      layer: 
#      listener: 
#      mock: 
#      owner: 
#      path: 
#      protocol: 
#      proxy: 
#      registry: 
#      stub: 
#      token: 
#      version: 
#      weight: 
#      accepts: 
#      actives: 
#      async: 
#      buffer: 
#      charset: 
#      client: 
#      cluster: 
#      codec: 
#      connections: 
#      default: 
#      host: 
#      iothreads: 
#      loadbalance: 
#      payload: 
#      queues: 
#      serialization: 
#      server: 
#      telnet: 
#      threadpool: 
#      threads: 
#      timeout: 
#      filter:  
#####################################################发布者通用配置信息###############################################################
        
##################################################发布者配置信息###############################################################
#    services:
#      - provider: 
#        accesslog:
#        async:
#        cluster: 
#        connections: 
#        contextpath: 
#        delay: 
#        deprecated:
#        document: 
#        dynamic:
#        executes: 
#        filter: 
#        group: 
#        interface: 
#        layer: 
#        listener: 
#        loadbalance: 
#        mock:
#        owner: 
#        path: 
#        protocol: 
#        proxy: 
#        ref:
#        register:
#        registry: 
#        retries: 
#        stub:
#        timeout: 
#        token:
#        version: 
#        weight:  
#        
##################################################发布者配置信息###############################################################
  