server:
  port: 0
  
spring:
  profiles:
    active:
      - dubbo
dubbo:

  application:
    name: demo-provider
    owner: laolei
    
#####################################################扫描注解的包###############################################################
  base-package: com.test.dubbo.provider
#####################################################扫描注解的包###############################################################
  

#####################################################发布者通用配置信息###############################################################
  provider:
    retries: -1
#    filter: 
#    exchanger: 
#    accepts: 
#    actives: 
#    async: 
#    buffer: 
#    charset: 
#    client: 
#    cluster: 
#    codec: 
#    connections: 
#    contextpath: 
#    default: 
#    dispatcher: 
#    host: 
#    iothreads: 
#    loadbalance: 
#    networker: 
#    payload: 
#    port: 
#    prompt: 
#    queues: 
#    serialization: 
#    server: 
#    status: 
#    telnet: 
#    threadpool: 
#    threads: 
#    timeout: 
#    transporter: 
#    wait:   
#####################################################发布者通用配置信息###############################################################

#####################################################发布者配置信息###############################################################
#  services:
#    - interface-class: 
#      interface: 
#      exported: 
#      methods:
#        - 
#      path: 
#      ref: 
#      unexported: 
#      exported-urls:
#        - 
#####################################################发布者配置信息###############################################################
  