server:
  port: 0
  
spring:
  profiles:
    active:
      - dubbo
      
  dubbo:
    application:
      name: demo-consumer
      owner: laolei
      
#####################################################扫描注解的包###############################################################
    base-package: com.test.dubbo.consumer
#####################################################扫描注解的包###############################################################
        
#####################################################消费者默认配置###############################################################
    consumer:
      lazy: true
      timeout: 1000 
      check: true
      
#####################################################消费者默认配置###############################################################
  
#####################################################消费者配置###############################################################
#    references:
#      - client: 
#        interface: 
#        interface-class: 
#        protocol: 
#        url: 
#        
####################################################消费者配置###############################################################