server:
  port: 0
  
logging:
  level:
    root: info
    org.springframework: warn
    org.apache.zookeeper: warn
    com.alibaba.dubbo: warn
spring:
  dubbo:
#####################################################注册中心###############################################################
    registry:
      protocol: zookeeper   # 注册中心支持的协议 包括 dubbo,multicast,zookeeper,redis 默认是zookeeper
      address: 127.0.0.1
      port: 2181
      client: zkclient # zookeeper 支持客户端包括 curator和zkclient,如果不配置，默认使用zkclient 
      register: true
      session: -1
      check: false
#      dynamic: 
#      file: 
#      username:  
#      password: 
#      subscribe: 
#      timeout: 
#      version: 
#      wait: 
#      id: 
#      transport: netty
#####################################################注册中心###############################################################
  
#####################################################监控中心###############################################################
#    monitor:
#      address: 
#      protocol: 
#################################################监控中心###############################################################
  
#####################################################模块信息###############################################################
#    module:
#      name: 
#      organization: 
#      owner: 
#      version: 
#####################################################模块信息###############################################################
  
#####################################################协议信息###############################################################
    
    protocol:
      name: dubbo
      serialization: hessian2
#      accepts: 
#      accesslog:
#      buffer: 
#      charset: 
#      client: 
#      codec: 
#      contextpath: 
#      dispatcher: 
#      heartbeat: 
#      host: 
#      id: 
#      iothreads: 
#      path: 
#      payload: 
#      port: 
#      queues: 
#      register:
#      server: 
#      telnet: 
#      threadpool: 
#      threads: 
#      transporter: 
      
#    protocols:
#      - name: dubbo
#        serialization: nativejava
#      - name: dubbo
#        serialization: hessian2
#      - name: dubbo
#        serialization: fastjson
#      - name: dubbo
#        serialization: dubbo
#      - name: rmi
#      - name: http
#      - name: hessian
#      - name: thrift
#      - name: webservice
####################################################协议信息###############################################################
  